INSERT INTO users (name, email) VALUES
('Filipe Rodrigues','filipe.rodrigues@example.com'),
('Frederico Pereira', 'frederico.pereira@example.com'),
('Alice Souza', 'alice.souza@example.com'),
('Raiza Andrade', 'raiza.andrade@example.com'),
('Lucas Santos', 'lucas.santos@example.com'),
('Marcela Kramer', 'marcela.kramer@example.com'),
('Caio Quirino', 'caio.quirino@example.com'),
('Sammuel Luna', 'sammuel.luna@example.com'),
('Raqueline Gomes', 'raqueline.gomes@example.com'),
('Lucas Silva', 'lucas.silva@example.com'),
('Maicon Souza', 'maicon.souza@example.com'),
('Gabriel Sousa', 'gabriel.sousa@example.com'),
('Jose Silva', 'jose.silva@example.com'),
('Luis Bernardo', 'luis.bernardo@example.com'),
('Sofia Silva', 'sofia.silva@example.com'),
('Rafael Bueno', 'rafael.bueno@example.com'),
('Simon Castro', 'simon.castro@example.com'),
('Arthur Miranda', 'arthur.miranda@example.com'),
('Gabriel Melo', 'gabriel.melo@example.com'),
('Gabriel Nascimento', 'gabriel.nascimento@example.com'),
('Mellanie Sousa', 'mellanie.sousa@example.com'),
('Gabriel Chaves', 'gabriel.chaves@example.com'),
('Islan Figueirêdo', 'islan.figueiredo@example.com'),
('Lucas Endress', 'lucas.endress@example.com'),
('Lavínia Morais', 'lavinia.morais@example.com'),
('Peter Costa', 'peter.costa@example.com'),
('Antonio Costa', 'antonio.costa@example.com'),
('João Dias', 'joao.dias@example.com'),
('Johnner Castro', 'johnner.castro@example.com');


